[ phases.setup ]
nixPkgs = [ "dotnet-sdk_8" ]

[ phases.build ]
cmds = [
  "dotnet restore",
  "dotnet publish Sparkle.Api/Sparkle.Api.csproj -c Release -o /app/out"
]

[ deploy ]
startNode = "dotnet /app/out/Sparkle.Api.dll"
healthcheckPath = "/swagger"
